import os
from typing import Dict, Any

TARGETS = {
    "openrouter": "https://openrouter.ai/api/v1",
    "openai": "https://api.openai.com/v1",
    "anthropic": "https://api.anthropic.com/v1",
    "gemini": "https://generativelanguage.googleapis.com/v1beta",
    "groq": "https://api.groq.com/openai/v1",
    "cohere": "https://api.cohere.com/v1",
    "mistral": "https://api.mistral.ai/v1",
    "deepseek": "https://api.deepseek.com/v1",
    "azure_openai": "https://{resource}.openai.azure.com/openai",
    "aws_bedrock": "https://bedrock-runtime.{region}.amazonaws.com",
    "ai21": "https://api.ai21.com/studio/v1",
    "aleph_alpha": "https://api.aleph-alpha.com",
    "pinecone": "https://api.pinecone.io",
    "weaviate": "https://{cluster}.weaviate.network",
    "qdrant": "https://{cluster}.cloud.qdrant.io",
    "chroma": "http://localhost:8000",
    "milvus": "https://{cluster}.milvus.io",
    "pgvector": "http://localhost:5432",
    "redis_vector": "http://localhost:6379",
    "brave": "https://api.search.brave.com",
    "serpapi": "https://serpapi.com",
    "tavily": "https://api.tavily.com",
    "exa": "https://api.exa.ai",
    "perplexity": "https://api.perplexity.ai",
    "bing": "https://api.bing.microsoft.com/v7.0",
    "google_custom_search": "https://www.googleapis.com/customsearch/v1",
    "github": "https://api.github.com",
    "gitlab": "https://gitlab.com/api/v4",
    "bitbucket": "https://api.bitbucket.org/2.0",
    "azure_devops": "https://dev.azure.com",
    "aws": "https://sts.amazonaws.com",
    "gcp": "https://cloud.googleapis.com",
    "azure": "https://management.azure.com",
    "supabase": "https://{project}.supabase.co",
    "firebase": "https://firebase.googleapis.com",
    "mongodb": "https://cloud.mongodb.com",
    "planetscale": "https://api.planetscale.com",
    "neon": "https://console.neon.tech/api/v2",
    "upstash": "https://api.upstash.com",
    "slack": "https://slack.com/api",
    "discord": "https://discord.com/api/v10",
    "telegram": "https://api.telegram.org",
    "twilio": "https://api.twilio.com/2010-04-01",
    "sendgrid": "https://api.sendgrid.com/v3",
    "mailgun": "https://api.mailgun.net/v3",
    "postmark": "https://api.postmarkapp.com",
    "resend": "https://api.resend.com",
    "langsmith": "https://api.smith.langchain.com",
    "langfuse": "https://cloud.langfuse.com/api/public",
    "weights_biases": "https://api.wandb.ai",
    "arize": "https://api.arize.com",
    "phoenix": "https://app.phoenix.arize.com",
    "promptlayer": "https://api.promptlayer.com",
    "helicone": "https://api.hconeai.com",
    "replicate": "https://api.replicate.com/v1",
    "stability": "https://api.stability.ai/v2beta",
    "cloudinary": "https://api.cloudinary.com/v1_1",
    "imgix": "https://api.imgix.com",
    "unsplash": "https://api.unsplash.com",
    "huggingface": "https://api-inference.huggingface.co",
    "assemblyai": "https://api.assemblyai.com/v2",
    "elevenlabs": "https://api.elevenlabs.io/v1",
    "openvoice": "https://api.openvoice.com",
    "whisper": "https://api.openai.com/v1",
    "deepgram": "https://api.deepgram.com/v1",
    "rev_ai": "https://api.rev.ai",
    "notion": "https://api.notion.com/v1",
    "airtable": "https://api.airtable.com/v0",
    "trello": "https://api.trello.com/1",
    "asana": "https://app.asana.com/api/1.0",
    "linear": "https://api.linear.app/graphql",
    "jira": "https://api.atlassian.com",
    "confluence": "https://api.atlassian.com",
    "stripe": "https://api.stripe.com/v1",
    "paypal": "https://api.paypal.com/v1",
    "shopify": "https://{shop}.myshopify.com/admin/api/2024-01",
    "auth0": "https://{domain}.auth0.com",
    "okta": "https://{domain}.okta.com",
    "1password": "https://api.1password.com",
}

SERVICE_CONFIGS = {
    "notion": {"auth_type": "bearer", "header_name": "Authorization"},
    "airtable": {"auth_type": "bearer", "header_name": "Authorization"},
    "twilio": {"auth_type": "basic", "header_name": "Authorization"},
    "sendgrid": {"auth_type": "bearer", "header_name": "Authorization"},
    "stripe": {"auth_type": "bearer", "header_name": "Authorization"},
    "auth0": {"auth_type": "bearer", "header_name": "Authorization"},
    "shopify": {"auth_type": "bearer", "header_name": "X-Shopify-Access-Token"},
    "deepgram": {"auth_type": "bearer", "header_name": "Authorization"},
    "linear": {"auth_type": "bearer", "header_name": "Authorization"},
    "replicate": {"auth_type": "token", "header_name": "Authorization"},
}

HOP_BY_HOP_HEADERS = {
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailers",
    "transfer-encoding",
    "upgrade",
}

def get_cors_origins() -> list[str]:
    return [
        o.strip()
        for o in os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://localhost:8080").split(",")
        if o.strip()
    ]
